Prefix: '&6&lT3SL4Bomb &8» '
Settings:
  enabled-worlds:
    - 'world'
    - 'orman'
  explosive-range: 4.0
  obsidian: true
  amount: 3
Item:
  name: '&6&lBovem Bomba'
  lore:
    - '&r  '
    - '&7Fırlattığınız alanda patlama yaratır'
    - '&7ama obsidyenleri patlatmaz.'
    - '&eTNT &7kullanarak, obsidyenleri'
    - '&7patlatabilirsiniz.'
    - '&r     '
    - '&6&lDEĞERLİ BOMBA'
Commands:
  help1: '&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m[&6 &lT3SL4Bomb &8&l&m]&f&l&m-&8&l&m-&f&l&m-&8&l&m-&f&l&m-&8&l&m-'
  help2: '&a/tb take &bAdet &f»&eBelirttiğin Miktarda %kartopu% &eAlırsın.'
  help3: '&a/tb give &bOyuncu &cAdet &f»&eBelirttiğin Oyuncuya %kartopu% &eVerir.'
  help4: '&a/tb reload &f»&eEklentiyi Yeniler'
Messages:
  reload: "&eEklenti Başarılı Bir Şekilde Yenilendi."
  perm: "&cDostum Maalesef Bunun İçin Yetkin Yok."
  world: "&cDostum &bMaalesef %kartopu% Bulunduğun Dünyada Kullanılamaz."
  add: "&eEnvanterine &6%adet% &eTane %kartopu% &eEklendi."
  give: "&b%player% &eAdlı Oyuncunun Envanterine &6%adet% &eTane %kartopu% &eEklendi."
  arg-give: "&eDoğru Kullanım: &b/tb give &cOyuncu &eAdet"
  arg-take: "&eDoğru Kullanım &b/tb take &bAdet"
  player: "&eBelirtilen Oyuncu Bulunamadı!"
  console: "&cDostum Bu Komutu Konsoldan Kullanamazsın!"
  online: "&b%player% &eAdlı Oyuncu Çevrimiçi Değil."