name: T3SL4Bomb
version: 04.02.2021
author: SYN_T3SL4
main: me.t3sl4.snowball.T3SL4Bomb
depend: [WorldGuard, WorldEdit]

commands:
  tb:
    description: Main command of T3SL4Bomb.
    aliases: [baskin, kartopu, kt]